### ISSUE TITLE
支持 Goner 初始化完成和销毁前的钩子函数

### ISSUE THREAD

**Issue by shenweijiekdel** [gone-io/gone#3]
类似 SpringBoot 的 @PostConstruct 和 @PreDestroy 标记方法的功能

有些场景可能需要在 Goner 初始化完成后或者销毁之前需要做一些业务上的流程

**Comment by Degfy** [comment]
https://goner.fun/zh/guide/core-concept.html#%F0%9F%98%87angel-%E5%A4%A9%E4%BD%BF
