### ISSUE TITLE
Gone gin 的堆栈打印大多是中间件附近的信息

### ISSUE THREAD

**Issue by shenweijiekdel** [gone-io/gone#6]
如题

**Comment by Degfy** [comment]
error 在go中只是一个值，并不携带堆栈信息，仅依赖框架捕获错误，只能拿到捕获处的堆栈；如果希望打印错误源头的堆栈，需要将错误包裹一下，将普通的error转为`gone.Error`，`gone.Error`可以携带当前堆栈信息 ：
例如：
```go
if err != nil {
    return  gin.ToError(err)
}
```
